
# 生产环境
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-wait: 1000
        max-active: 100
        max-idle: 50
  mvc:
    static-path-pattern: /static/**
  freemarker:
    cache: true


# 微信相关配置
wx:
  token:
  appID:
  appsecret:
  host:

